# Generated by Django 5.0.6 on 2026-07-03 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('is_living', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='people/')),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='trees.tree')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('diff', models.JSONField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log', to='people.person')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('parent_child', 'Parent-child'), ('spouse', 'Spouse')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_biological', models.BooleanField(default=True)),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='people.person')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='people.person')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='trees.tree')),
            ],
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.CheckConstraint(check=models.Q(('person_a', models.F('person_b')), _negated=True), name='no_self_relationship'),
        ),
    ]
