# Generated by Django 5.0.6 on 2026-07-03 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_mediaitem_sharelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('birth', 'Birth'), ('marriage', 'Marriage'), ('death', 'Death'), ('education', 'Education'), ('career', 'Career'), ('residence', 'Residence'), ('immigration', 'Immigration / migration'), ('military', 'Military'), ('religious', 'Religious'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='people.person')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
